# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/griffe-quarto',
                'doc_host': 'https://hamelsmu.github.io',
                'git_url': 'https://github.com/hamelsmu/griffe-quarto',
                'lib_path': 'griffe_quarto'},
  'syms': { 'griffe_quarto.tpl': { 'griffe_quarto.tpl._find_quarto_cfg': ('tpl.html#_find_quarto_cfg', 'griffe_quarto/tpl.py'),
                                   'griffe_quarto.tpl._proj_templates': ('tpl.html#_proj_templates', 'griffe_quarto/tpl.py'),
                                   'griffe_quarto.tpl._return_pth': ('tpl.html#_return_pth', 'griffe_quarto/tpl.py'),
                                   'griffe_quarto.tpl._set_directory': ('tpl.html#_set_directory', 'griffe_quarto/tpl.py'),
                                   'griffe_quarto.tpl.env': ('tpl.html#env', 'griffe_quarto/tpl.py')}}}
