# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/griffe-quarto',
                'doc_host': 'https://hamelsmu.github.io',
                'git_url': 'https://github.com/hamelsmu/griffe-quarto',
                'lib_path': 'griffe_quarto'},
  'syms': { 'griffe_quarto.loader': { 'griffe_quarto.loader._find_quarto_cfg': ('loader.html#_find_quarto_cfg', 'griffe_quarto/loader.py'),
                                      'griffe_quarto.loader._proj_templates': ('loader.html#_proj_templates', 'griffe_quarto/loader.py'),
                                      'griffe_quarto.loader._return_pth': ('loader.html#_return_pth', 'griffe_quarto/loader.py'),
                                      'griffe_quarto.loader._set_directory': ('loader.html#_set_directory', 'griffe_quarto/loader.py'),
                                      'griffe_quarto.loader.env': ('loader.html#env', 'griffe_quarto/loader.py')}}}
